const ExcelJS = require('exceljs');
const { format } = require('date-fns');

/**
 * Format date nicely for Excel & Summary
 */
const formatDate = (dateVal, withTime = false) => {
  if (!dateVal) return '-';
  try {
    const d = new Date(dateVal);
    if (isNaN(d.getTime())) return '-';
    return format(d, withTime ? 'dd-MM-yyyy HH:mm' : 'dd-MM-yyyy');
  } catch (err) {
    return '-';
  }
};

/**
 * Generate Excel Workbook for any Report Type
 */
const generateReportExcel = async ({ reportType, reportTitle, filters = {}, records = [], kpis = {} }) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Maruti Denim ERP System';
  workbook.created = new Date();

  const istNow = format(new Date(), 'dd-MM-yyyy HH:mm:ss');

  // ==========================================
  // SHEET 1: Report Summary
  // ==========================================
  const summarySheet = workbook.addWorksheet('Report Summary', { views: [{ showGridLines: true }] });

  // Title Block
  summarySheet.mergeCells('A1:F1');
  const titleCell = summarySheet.getCell('A1');
  titleCell.value = 'MARUTI NANDAN DENIM PVT LTD';
  titleCell.font = { name: 'Calibri', size: 16, bold: true, color: { argb: 'FFFFFFFF' } };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F2A47' } };
  titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
  summarySheet.getRow(1).height = 30;

  summarySheet.mergeCells('A2:F2');
  const subTitleCell = summarySheet.getCell('A2');
  subTitleCell.value = `${reportTitle.toUpperCase()} - MANAGEMENT MIS REPORT`;
  subTitleCell.font = { name: 'Calibri', size: 13, bold: true, color: { argb: 'FF1E293B' } };
  subTitleCell.alignment = { horizontal: 'center', vertical: 'middle' };
  summarySheet.getRow(2).height = 24;

  summarySheet.addRow([]);

  // Report Info Block
  summarySheet.addRow(['Report Title:', reportTitle]);
  summarySheet.addRow(['Generated Date & Time (IST):', istNow]);
  summarySheet.addRow(['Report Period:', `${filters.fromDate || 'Beginning'} to ${filters.toDate || 'Present'}`]);
  summarySheet.addRow(['Total Records:', records.length]);
  summarySheet.addRow(['Generated By:', 'Admin System']);

  // Format Labels
  for (let r = 4; r <= 8; r++) {
    const row = summarySheet.getRow(r);
    row.getCell(1).font = { bold: true, color: { argb: 'FF475569' } };
    row.getCell(2).font = { bold: true, color: { argb: 'FF0F2A47' } };
  }

  summarySheet.addRow([]);

  // Filter Details Block
  summarySheet.addRow(['APPLIED FILTERS SUMMARY']).font = { bold: true, size: 11, color: { argb: 'FF0F2A47' } };
  const filterKeys = Object.keys(filters).filter(k => filters[k] && filters[k] !== 'All');
  if (filterKeys.length === 0) {
    summarySheet.addRow(['Filters:', 'None (All Records Included)']);
  } else {
    filterKeys.forEach(k => {
      summarySheet.addRow([`${k}:`, String(filters[k])]);
    });
  }

  summarySheet.addRow([]);

  // KPI Summary Metrics Block
  summarySheet.addRow(['KEY PERFORMANCE INDICATORS (KPIs)']).font = { bold: true, size: 11, color: { argb: 'FF0F2A47' } };
  Object.entries(kpis).forEach(([kpiKey, kpiVal]) => {
    const label = kpiKey.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
    summarySheet.addRow([label, typeof kpiVal === 'number' ? kpiVal : String(kpiVal)]);
  });

  // Column Widths for Summary Sheet
  summarySheet.getColumn(1).width = 30;
  summarySheet.getColumn(2).width = 40;

  // ==========================================
  // SHEET 2: Detailed Data Sheet
  // ==========================================
  const dataSheetName = reportTitle.substring(0, 30);
  const dataSheet = workbook.addWorksheet(dataSheetName, { views: [{ state: 'frozen', ySplit: 1, showGridLines: true }] });

  if (!records || records.length === 0) {
    dataSheet.addRow(['No records found for the selected filters.']).font = { italic: true, color: { argb: 'FF64748B' } };
    const buffer = await workbook.xlsx.writeBuffer();
    return buffer;
  }

  // Define Columns & Alignments per Report Type
  let columnsConfig = [];

  switch (reportType) {
    case 'gate-pass':
      columnsConfig = [
        { header: 'Sr. No.', key: 'srNo', width: 8, align: 'center' },
        { header: 'Gate Pass No.', key: 'gatePassNumber', width: 16, align: 'center' },
        { header: 'Gate Pass Date', key: 'date', width: 14, align: 'center', isDate: true },
        { header: 'Party / Company Name', key: 'companyName', width: 28, align: 'left' },
        { header: 'Purpose', key: 'purpose', width: 22, align: 'left' },
        { header: 'Material Type', key: 'materialType', width: 14, align: 'center' },
        { header: 'Item Count', key: 'itemCount', width: 12, align: 'right', numFmt: '#,##0' },
        { header: 'Total Qty', key: 'totalQuantity', width: 12, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Returnable Qty', key: 'returnableQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Returned Qty', key: 'returnedQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Balance Qty', key: 'balanceReturnableQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Gate Pass Status', key: 'gatePassStatus', width: 14, align: 'center' },
        { header: 'Return Status', key: 'returnStatus', width: 18, align: 'center' },
        { header: 'Created By', key: 'createdBy', width: 14, align: 'left' },
        { header: 'Created Date', key: 'createdAt', width: 16, align: 'center', isDate: true, withTime: true },
        { header: 'Remarks', key: 'remarks', width: 25, align: 'left' }
      ];
      break;

    case 'material-inward':
      columnsConfig = [
        { header: 'Sr. No.', key: 'srNo', width: 8, align: 'center' },
        { header: 'Inward No.', key: 'inwardNumber', width: 16, align: 'center' },
        { header: 'Inward Date & Time', key: 'inwardDate', width: 18, align: 'center', isDate: true, withTime: true },
        { header: 'Gate Pass No.', key: 'gatePassNumber', width: 16, align: 'center' },
        { header: 'Gate Entry No.', key: 'gateEntryNumber', width: 16, align: 'center' },
        { header: 'Challan / Invoice No.', key: 'challanInvoiceNumber', width: 20, align: 'left' },
        { header: 'Party / Company Name', key: 'partyName', width: 26, align: 'left' },
        { header: 'Item Count', key: 'itemCount', width: 12, align: 'right', numFmt: '#,##0' },
        { header: 'Rec. Qty', key: 'receivedQuantity', width: 12, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Subtotal (₹)', key: 'subtotal', width: 15, align: 'right', numFmt: '"₹" #,##0.00', isSum: true },
        { header: 'CGST (₹)', key: 'totalCgst', width: 14, align: 'right', numFmt: '"₹" #,##0.00', isSum: true },
        { header: 'SGST (₹)', key: 'totalSgst', width: 14, align: 'right', numFmt: '"₹" #,##0.00', isSum: true },
        { header: 'IGST (₹)', key: 'totalIgst', width: 14, align: 'right', numFmt: '"₹" #,##0.00', isSum: true },
        { header: 'Total GST (₹)', key: 'totalGst', width: 15, align: 'right', numFmt: '"₹" #,##0.00', isSum: true },
        { header: 'Grand Total (₹)', key: 'grandTotal', width: 16, align: 'right', numFmt: '"₹" #,##0.00', isSum: true },
        { header: 'Created By', key: 'createdBy', width: 14, align: 'left' },
        { header: 'Remarks', key: 'remarks', width: 22, align: 'left' }
      ];
      break;

    case 'returnable-material':
    case 'pending-returns':
      columnsConfig = [
        { header: 'Sr. No.', key: 'srNo', width: 8, align: 'center' },
        { header: 'Gate Pass No.', key: 'gatePassNumber', width: 16, align: 'center' },
        { header: 'Gate Pass Date', key: 'date', width: 14, align: 'center', isDate: true },
        { header: 'Party / Company Name', key: 'companyName', width: 26, align: 'left' },
        { header: 'Item Description', key: 'itemName', width: 24, align: 'left' },
        { header: 'Original Qty', key: 'originalQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Returnable Qty', key: 'returnableQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Returned Qty', key: 'returnedQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Pending Qty', key: 'pendingQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        ...(reportType === 'pending-returns' ? [{ header: 'Days Pending', key: 'daysPending', width: 14, align: 'right', numFmt: '#,##0' }] : []),
        { header: 'Last Inward Date', key: 'lastInwardDate', width: 16, align: 'center', isDate: true, withTime: true },
        { header: 'Gate Pass Status', key: 'gatePassStatus', width: 14, align: 'center' },
        { header: 'Return Status', key: 'returnStatus', width: 18, align: 'center' },
        { header: 'Remarks', key: 'remarks', width: 22, align: 'left' }
      ];
      break;

    case 'gate-pass-closure':
      columnsConfig = [
        { header: 'Sr. No.', key: 'srNo', width: 8, align: 'center' },
        { header: 'Gate Pass No.', key: 'gatePassNumber', width: 16, align: 'center' },
        { header: 'Gate Pass Date', key: 'date', width: 14, align: 'center', isDate: true },
        { header: 'Party / Company Name', key: 'companyName', width: 26, align: 'left' },
        { header: 'Orig. Returnable Qty', key: 'originalReturnableQuantity', width: 18, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Total Returned Qty', key: 'totalReturnedQuantity', width: 18, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Final Inward No.', key: 'finalInwardNumber', width: 18, align: 'center' },
        { header: 'Final Inward Date', key: 'finalInwardDate', width: 16, align: 'center', isDate: true, withTime: true },
        { header: 'Closure Date', key: 'closureDate', width: 16, align: 'center', isDate: true, withTime: true },
        { header: 'Total Days to Close', key: 'totalDaysToClose', width: 16, align: 'right', numFmt: '#,##0' },
        { header: 'Gate Pass Status', key: 'gatePassStatus', width: 14, align: 'center' },
        { header: 'Return Status', key: 'returnStatus', width: 18, align: 'center' }
      ];
      break;

    case 'party-summary':
      columnsConfig = [
        { header: 'Sr. No.', key: 'srNo', width: 8, align: 'center' },
        { header: 'Party / Company Name', key: 'partyName', width: 28, align: 'left' },
        { header: 'Total Gate Passes', key: 'totalGatePasses', width: 16, align: 'right', numFmt: '#,##0', isSum: true },
        { header: 'Open Passes', key: 'openGatePasses', width: 14, align: 'right', numFmt: '#,##0', isSum: true },
        { header: 'Closed Passes', key: 'closedGatePasses', width: 14, align: 'right', numFmt: '#,##0', isSum: true },
        { header: 'Returnable Qty', key: 'totalReturnableQuantity', width: 16, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Returned Qty', key: 'totalReturnedQuantity', width: 16, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Pending Qty', key: 'totalPendingQuantity', width: 16, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Oldest Pending Date', key: 'oldestPendingDate', width: 18, align: 'center', isDate: true },
        { header: 'Grand Value (₹)', key: 'totalGrandTotal', width: 18, align: 'right', numFmt: '"₹" #,##0.00', isSum: true }
      ];
      break;

    case 'combined':
    default:
      columnsConfig = [
        { header: 'Sr. No.', key: 'srNo', width: 8, align: 'center' },
        { header: 'Gate Pass No.', key: 'gatePassNumber', width: 16, align: 'center' },
        { header: 'GP Date', key: 'date', width: 14, align: 'center', isDate: true },
        { header: 'Party / Company Name', key: 'partyName', width: 26, align: 'left' },
        { header: 'Item Description', key: 'itemDescription', width: 24, align: 'left' },
        { header: 'Original Qty', key: 'originalQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Returnable Qty', key: 'returnableQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Inward No.', key: 'inwardNumber', width: 16, align: 'center' },
        { header: 'Inward Date', key: 'inwardDate', width: 16, align: 'center', isDate: true, withTime: true },
        { header: 'Received Qty', key: 'receivedQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Balance Qty', key: 'balanceQuantity', width: 14, align: 'right', numFmt: '#,##0.00', isSum: true },
        { header: 'Return Status', key: 'returnStatus', width: 18, align: 'center' }
      ];
      break;
  }

  // Set Header Columns
  dataSheet.columns = columnsConfig.map(c => ({
    header: c.header,
    key: c.key,
    width: c.width
  }));

  // Style Header Row
  const headerRow = dataSheet.getRow(1);
  headerRow.height = 25;
  headerRow.eachCell((cell, colNumber) => {
    cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F2A47' } };
    cell.alignment = { horizontal: columnsConfig[colNumber - 1]?.align || 'left', vertical: 'middle' };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FF0F2A47' } },
      left: { style: 'thin', color: { argb: 'FF1E293B' } },
      bottom: { style: 'medium', color: { argb: 'FF0F2A47' } },
      right: { style: 'thin', color: { argb: 'FF1E293B' } }
    };
  });

  // Enable AutoFilter
  const lastColLetter = String.fromCharCode(64 + columnsConfig.length);
  dataSheet.autoFilter = `A1:${lastColLetter}1`;

  // Add Data Rows
  records.forEach((rec, idx) => {
    const rowObj = { srNo: idx + 1 };
    columnsConfig.forEach(col => {
      if (col.key === 'srNo') return;
      let val = rec[col.key];

      if (col.isDate) {
        val = formatDate(val, col.withTime);
      }
      rowObj[col.key] = val !== undefined && val !== null ? val : '-';
    });

    const dataRow = dataSheet.addRow(rowObj);
    dataRow.height = 20;

    dataRow.eachCell((cell, colNumber) => {
      const config = columnsConfig[colNumber - 1];
      cell.alignment = { horizontal: config?.align || 'left', vertical: 'middle' };
      cell.border = {
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
      };

      if (config?.numFmt && typeof cell.value === 'number') {
        cell.numFmt = config.numFmt;
      }
    });
  });

  // Add Grand Total Row with Excel SUM formulas
  const totalRowObj = { srNo: '' };
  totalRowObj[columnsConfig[1].key] = 'TOTAL';

  columnsConfig.forEach((col, cIdx) => {
    if (col.isSum) {
      const colLetter = String.fromCharCode(65 + cIdx);
      const startRow = 2;
      const endRow = records.length + 1;
      totalRowObj[col.key] = { formula: `SUM(${colLetter}${startRow}:${colLetter}${endRow})` };
    }
  });

  const totalRow = dataSheet.addRow(totalRowObj);
  totalRow.height = 24;

  totalRow.eachCell((cell, colNumber) => {
    const config = columnsConfig[colNumber - 1];
    cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FF0F2A47' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
    cell.alignment = { horizontal: config?.align || 'left', vertical: 'middle' };
    cell.border = {
      top: { style: 'double', color: { argb: 'FF0F2A47' } },
      bottom: { style: 'double', color: { argb: 'FF0F2A47' } }
    };

    if (config?.numFmt) {
      cell.numFmt = config.numFmt;
    }
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return buffer;
};

module.exports = {
  generateReportExcel
};
